collections_dir: collections
collections:
  Cplusplus:
    output: true
    icon: https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/ISO_C%2B%2B_Logo.svg/140px-ISO_C%2B%2B_Logo.svg.png
  Linux:
    output: true
    icon: https://www.linux.org/styles/uix/uix/logo_small.png
  Vim:
    output: true
    icon: https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Vimlogo.svg/64px-Vimlogo.svg.png
  Android:
    output: true
    icon: https://developer.android.google.cn/static/images/branding/icons/android-blog-round-icon.svg
  Git:
    output: true
    icon: ../../assets/img/git.png
  MySQL:
    output: true
    icon: ../../assets/img/mysql.png
  DesignPattern:
    output: true
    icon: ../../assets/img/dp.png

defaults:
  - scope:
      path: ""
      type: "Cplusplus"
    values:
      layout: "collection"
  - scope:
      path: ""
      type: "Linux"
    values:
      layout: "collection"
  - scope:
      path: ""
      type: "Vim"
    values:
      layout: "collection"
  - scope:
      path: ""
      type: "Android"
    values:
      layout: "collection"
  - scope:
      path: ""
      type: "Git"
    values:
      layout: "collection"
  - scope:
      path: ""
      type: "MySQL"
    values:
      layout: "collection"
  - scope:
      path: ""
      type: "DesignPattern"
    values:
      layout: "collection"

markdown: kramdown
kramdown:
   input: GFM
   hard_wrap: true
#theme: minima
title: thomasl007
email: actml@outlook.com
